services:
  caddy:
    image: caddy:latest
    container_name: luoxu_caddy
    ports:
      - "15100:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - luoxu
      - web

  luoxu:
    image: ghcr.io/seele0oo/luoxu/luoxu:latest
    container_name: luoxu
    # ports:
    #   - "9008:9008"
    environment:
      - DATABASE_URL=postgresql://postgres:yourpassword@db:5432/luoxu_db
    depends_on:
      - db
    volumes:
      - luoxu_data:/app/data
      - ./config/config.toml:/app/config.toml

  db:
    image: ghcr.io/seele0oo/luoxu/luoxu-postgres-db:latest
    container_name: luoxu_db
    environment:
      POSTGRES_DB: luoxu_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    image: ghcr.io/seele0oo/luoxu/luoxu-web:latest
    container_name: luoxu_web
    # ports:
    #   - "3000:3000"
    environment:
      LUOXU_URL: http://luoxu:9008/luoxu
      # 这个是实际对外暴露的地址,建议设置为公网地址

volumes:
  pgdata:
  luoxu_data:
